[package]
name = "peertube-viewer-rs"
version = "1.4.0"
authors = ["Sosthène Guédon <sosthene.gued@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
peertube-api = {version = "*", path = "crates/peertube-api"}
preloadable-list = {version = "*", path = "crates/preloadable-list"}
tokio = { version = "0.2.21", features = ["rt-threaded", "rt-util", "process"] }
termion = "1"
chrono = "0.4.11"
rustyline = "6"
clap = { version = "2", features = ["yaml"] }
toml = "0.5.6"
unicode-width = "0.1.7"
directories = "2"
futures = "0.3.5"


[workspace]
members = ["crates/peertube-api/", "crates/peertube-ser/"]

[build-dependencies]
clap = { version = "2", features = ["yaml"] }

