[package]
name = "peertube-viewer"
version = "0.1.0"
authors = ["Sosthène Guédon <sosthene.gued@gmail.com>"]
edition = "2018"

[dependencies]
peertube-api = {version = "*", path = "crates/peertube-api"}
tokio = { version = "0.2", features = ["full"] }
termion = "1.5"
chrono = "0.4"
rustyline = "6.1.1"
clap = "2.33.0" 
toml = "0.5"


[workspace]
members = ["crates/peertube-api/", "crates/peertube-ser/"]
