[package]
name = "peertube-viewer"
version = "0.1.0"
authors = ["Sosthène Guédon <sosthene.gued@gmail.com>"]
edition = "2018"

[dependencies]
peertube-api = {version = "*", path = "crates/peertube-api"}
cli-ui= {version = "*", path = "crates/cli-ui"}
tokio = { version = "0.2", features = ["full"] }
termion = "1.5"


[workspace]
members = ["crates/peertube-api/", "crates/peertube-ser/", "crates/cli-ui/"]
