[package]
name = "peertube-viewer-rs"
version = "1.7.2"
authors = ["Sosthène Guédon <sosthene.gued@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
peertube-api = {version = "*", path = "crates/peertube-api"}
preloadable-list = {version = "*", path = "crates/preloadable-list"}
ureq = "1"
termion = "1"
chrono = "0.4.13"
rustyline = { version = "6", default-features=false}
clap = { version = "2", features = ["yaml"] }
toml = "0.5.6"
unicode-width = "0.1.8"
directories = "3.0.0"


[workspace]
members = ["crates/peertube-api/", "crates/peertube-ser/"]

[build-dependencies]
clap = { version = "2", features = ["yaml"] }

[profile.release]
lto="fat"
opt-level="s"
