[package]
name = "peertube-viewer-rs"
version = "1.7.3"
authors = ["Sosthène Guédon <dev@peertube-viewer.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
peertube-api = {version = "*", path = "crates/peertube-api"}
preloadable-list = {version = "*", path = "crates/preloadable-list"}
ureq = "1"
termion = "1"
chrono = "0.4"
rustyline = { version = "7", default-features=false}
clap = { version = "2", features = ["yaml"] }
toml = "0.5"
unicode-width = "0.1"
directories = "3"


[workspace]
members = ["crates/peertube-api/", "crates/peertube-ser/"]

[build-dependencies]
clap = { version = "2", features = ["yaml"] }

[profile.release]
lto="fat"
opt-level="s"
