[package]
name = "peertube-viewer-rs"
version = "1.0.0"
authors = ["Sosthène Guédon <sosthene.gued@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
peertube-api = {version = "*", path = "crates/peertube-api"}
tokio = { version = "0.2.20", features = ["rt-threaded", "rt-util", "process"] }
termion = "1.5.5"
chrono = "0.4.11"
rustyline = "6.1.2"
clap = "2.33.0"
toml = "0.5.6"
dirs = "2.0.2"


[workspace]
members = ["crates/peertube-api/", "crates/peertube-ser/"]

[build-dependencies]
clap = "2.33.0"

