[package]
name = "peertube-viewer-rs"
version = "1.8.0"
authors = ["Sosthène Guédon <dev@peertube-viewer.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
peertube-api = {version = "*", path = "crates/peertube-api"}
preloadable-list = {version = "*", path = "crates/preloadable-list"}
peertube-viewer-utils = {version = "*", path = "crates/peertube-viewer-utils"}
termion = "1"
chrono = "0.4"
rustyline = { version = "8", default-features=false}
clap = { version = "2", features = ["yaml"] }
toml = "0.5"
unicode-width = "0.1"
directories = "3"
textwrap = "0.13.1"
terminal_size = "0.1"
url = "2"
ureq = "2"

[workspace]
members = ["crates/peertube-api/", "crates/peertube-ser/", "crates/preloadable-list/", "crates/peertube-viewer-utils/"]

[build-dependencies]
clap = { version = "2", features = ["yaml"] }

[profile.release]
lto="fat"
opt-level="s"
