.\" Manpage for peertube-viewer-rs

.TH man  "2020" "1.2.0" "peertube-viewer-rs manpage"

.SH NAME
peertube-viewer a simple peertube cli browser

.SH SYNOPSIS
peertube-viewer [--player=player][--instance=instance][initial query or video url]


.SH DESCRIPTION
Allows you to search videos from a peertube instance with a similar interface to youtube-viewer

.B FEATURES 

.B search history 

.B instance selection

.B instance blacklist and whitelist
 
.B quality selection


.SH OPTIONS

.B --instance
overrides the instance set in the config file.

.B --[player/torrent-downloader]
overrides the player/torrent client set in the config file.

.B --[player/torrent-downloader]-args
overrides the player/torrent downloader arguments set in the config file.

.B --use-raw-url
Will pass the url to the seed file instead of the web url to the player.
This might be neccessary for some players(vlc) but some(mpv) don't need it and will even extract some information from it to display in their GUI.

.B --select-quality, -s
Will prompt you to chose the video quality when playing a video

.B --help ,-h
Display basic help.

.B --use-torrent
Use the provided torrent downloader instead of the video player

.B --config, -c 
Use a specified config file

.B --[no-]color
specify whether colors should be used

.B --[block/tag/let]-nsfw
Specify the behavior for nsfw videos (block them, add a nsfw tag in the search results or let them be)

.SH config
A config file can be put in `$XDG_CONFIG_HOME/peertube-viewer-rs/config.toml` or `/home/sos/.config/peertube-viewer-rs/config.toml`.
The expected format is TOML and an example of all configuration options can be obtained with the --print-full-example-config flag

.SH Online documentation
https://sostheneguedon.gitlab.io/peertube-viewer-rs/peertube-viewer-rs.html

.SH REPORTING BUGS

Gitlab issue tracker : https://gitlab.com/SostheneGuedon/peertube-viewer-rs/issues

.SH AUTHOR

Written by Sosthène Guédon

