[general]

# available options: block, tag(add a nswf tag to search results), let(do nothing)
# default is tag
nsfw = "block"

# enable or disable, defaults to enable
colors = "disable"

# can be true or false
select-quality = true

# can be emacs or vi, defaults to emacs
edit-mode = "vi"

# If this option isn't present, the "BROWSER" environment variable is used
# If it isn't set, the default is Firefox
browser = "qutebrowser"

[player]
command = "mpv"
args = ["--volume=30"]

# can be true or false
use-raw-urls = true

[instances]
main = "skeptikon.fr"

# whitelist = ["video.ploud.fr"]
blacklist = ["peertube.social"]

[torrent]
command = "transmission-remote"
args = ["-a"]
