[package]
name = "cli-ui"
version = "0.1.0"
authors = ["Sosthène Guédon <sosthene.gued@gmail.com>"]
edition = "2018"


[dependencies]
tokio = { version = "0.2.0", features = ["full"] }
rustyline = "6.1.1"
