[package]
name = "peertube-api"
version = "0.1.0"
authors = ["Sosthène Guédon <sosthene.gued@gmail.com>"]
edition = "2018"

[dependencies]
peertube-ser = {version = "*", path = "../peertube-ser"}


tokio = "0.2.21"
reqwest = "0.10.6"
nanoserde = "0.1.18"
chrono = "0.4.13"
