[package]
name = "peertube-api"
version = "0.1.0"
authors = ["Sosthène Guédon <sosthene.gued@gmail.com>"]
edition = "2018"

[dependencies]
peertube-ser = {version = "*", path = "../peertube-ser"}

reqwest = "0.10.4"
serde =  "1.0"
serde_json = "1.0"
