export COMPRESS_REGEX := '.*\.\(htm\|html\|json\|txt\|text\|js\|css\|xml\|svg\|ttf\)$'
build:
    mdbook build
    find book -type f -regex "$COMPRESS_REGEX" -exec gzip -9 -f -k {} \;
    find book -type f -regex "$COMPRESS_REGEX" -exec brotli -q 11 -f -k {} \;
